builders:
  json_models_builder:
    import: "package:serdes_json/builder.dart"
    builder_factories: ["jsonBuilder"]
    build_extensions: {".dart": [".multiply.g.part"]}
    auto_apply: dependents
    build_to: cache
    applies_builders: ["source_gen|combining_builder"]
