name: serdes_json

environment:
  sdk: ">=2.3.0 <3.0.0"

dependencies:
  analyzer: ">=0.37.0 <0.40.0"
  build: ^1.0.0
  source_gen:
  equatable: ^1.0.1
  recase: ^3.0.0
  localized_string: ^0.1.1

dev_dependencies:
  flutter_test:
    sdk: flutter
