name: drivers
description: A new Flutter package.
version: 0.0.1
author:
homepage: no page yet

environment:
  sdk: ">=2.7.0 <3.0.0"
  flutter: ">=1.17.0"

dependencies:
  # workspace
  serdes_json:
    path: ../serdes_json

  flutter:
    sdk: flutter

  flutter_localizations:
    sdk: flutter

  flutter_cupertino_localizations: ^1.0.1

  optional: ^5.0.0
  decimal: ^0.3.5
  get_it: ^5.0.1
  localized_string: ^0.1.0

  dio: ^3.0.9

  bloc: ^6.0.1
  flutter_bloc: ^6.0.1
  bloc_test: ^7.0.0

  flutter_svg: ^0.18.1
  encrypt: ^4.0.3
  crypto: ^2.1.5
  password: ^1.0.0

  intl:
  intl_translation:

  firebase_core: ^0.5.0
  firebase_crashlytics: ^0.2.4

  hive: ^1.4.4+1
  hive_flutter: ^0.3.1

  data_connection_checker: ^0.3.4
  connectivity: 0.4.9+2
  cached_network_image: ^2.5.0

dev_dependencies:
  build_runner:
  hive_generator: ^0.7.1
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter.
flutter:

# To add assets to your package, add an assets section, like this:
# assets:
#   - images/a_dot_burr.jpeg
#   - images/a_dot_ham.jpeg
#
# For details regarding assets in packages, see
# https://flutter.dev/assets-and-images/#from-packages
#
# An image asset can refer to one or more resolution-specific "variants", see
# https://flutter.dev/assets-and-images/#resolution-aware.

# To add custom fonts to your package, add a fonts section here,
# in this "flutter" section. Each entry in this list should have a
# "family" key with the font family name, and a "fonts" key with a
# list giving the asset and other descriptors for the font. For
# example:
# fonts:
#   - family: Schyler
#     fonts:
#       - asset: fonts/Schyler-Regular.ttf
#       - asset: fonts/Schyler-Italic.ttf
#         style: italic
#   - family: Trajan Pro
#     fonts:
#       - asset: fonts/TrajanPro.ttf
#       - asset: fonts/TrajanPro_Bold.ttf
#         weight: 700
#
# For details regarding fonts in packages, see
# https://flutter.dev/custom-fonts/#from-packages
